all:
  children:
    routers:
      hosts:
        Cat8K_R1:
          ansible_host: 2.2.2.2
          ansible_user: "{{ vault_ansible_user }}"
          ansible_password: "{{ vault_ansible_password }}"
          ansible_network_os: ios
          ansible_connection: network_cli
        IOS_Router:
          ansible_host: 3.3.3.3
          ansible_user: "{{ vault_ansible_user }}"
          ansible_password: "{{ vault_ansible_password }}"
          ansible_network_os: ios
          ansible_connection: network_cli
          ansible_ssh_common_args: '-oKexAlgorithms=+diffie-hellman-group14-sha1'
